### ISSUE TITLE
[Need support]: New element locator have not been found. There is no reference data to selector in the database.

### ISSUE THREAD

**Issue by AdarshSingh003** [healenium/healenium-example-maven#19]
### Describe the problem

I have read your FAQ section and also update the latest version of healenium web, selenium java according to the docker-compose.yml file but still get the same issue i am using docker please healp it is very urgent.

**Console log**.

[RemoteTestNG] detected TestNG version 7.8.0
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 2 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 10 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 18 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 1 ms.
[main] WARN org.testng.internal.Configuration - Detected a static method [demoHealenium.HealeniumDemoWithDocker.startTest()]. Static configuration methods can cause  unexpected behavior.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 1 ms.
[main] WARN org.testng.internal.Configuration - Detected a static method [demoHealenium.HealeniumDemoWithDocker.endTest()]. Static configuration methods can cause  unexpected behavior.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 1 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 1 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 1 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 1 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 1 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [TestNG] Running:
  C:\Users\DYNAMIC MONSTERS\AppData\Local\Temp\testng-eclipse--1771937419\testng-customsuite.xml

[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 114.0.5735.90 (resolved driver for Chrome 114)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\DYNAMIC MONSTERS\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 31948
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Sep 11, 2023 5:23:57 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 114, so returning the closest version found: 112
[main] INFO org.testng.internal.Utils - [Utils] DynamicGraphHelper.createDynamicGraph() took 7 ms.
[main] WARN healenium - Failed to find an element using locator By.cssSelector: [name='Name']
[main] WARN healenium - Reason: no such element: Unable to locate element: {"method":"css selector","selector":"[name='Name']"}
  (Session info: chrome=114.0.5735.134)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c7149607805ddac2e88e937615951127, findElement {using=css selector, value=[name='Name']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.134, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\Users\DYNAMI~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59242}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:59242/devtoo..., se:cdpVersion: 114.0.5735.134, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: c7149607805ddac2e88e937615951127
[main] WARN healenium - Trying to heal...
[main] WARN healenium - New element locator have not been found. There is no reference data to selector in the database.
Make sure that: 
- There is selector on the page http://localhost:7878/healenium/selectors/ and type: single, if not then you have to run successful tests.
- Your locator was changed on the page and not in code.
FAILED: demoHealenium.HealeniumDemoWithDocker.healeniumDemoWithDocker
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"[name='Name']"}
  (Session info: chrome=114.0.5735.134)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c7149607805ddac2e88e937615951127, findElement {using=css selector, value=[name='Name']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.134, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\Users\DYNAMI~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59242}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:59242/devtoo..., se:cdpVersion: 114.0.5735.134, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: c7149607805ddac2e88e937615951127
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:23)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:60)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at jdk.proxy2/jdk.proxy2.$Proxy15.findElement(Unknown Source)
	at demoHealenium.HealeniumDemoWithDocker.healeniumDemoWithDocker(HealeniumDemoWithDocker.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================

[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@7c5df615: 53 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.jq.Main@12952aff: 137 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.FailedReporter@14b31e37: 89 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.XMLReporter@11c78080: 38 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.EmailableReporter2@616a06e3: 18 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.reporters.JUnitReportReporter@17222c11: 15 ms
[main] INFO org.testng.internal.Utils - [TestNG] Time taken by org.testng.internal.ExitCodeListener@2db15f70: 0 ms

and also i have attached my project please help i have tried all the possible solution ;-
[demo.zip](https://github.com/healenium/healenium-example-maven/files/12575787/demo.zip)

### Healenium Proxy version

1.3.0

### Healenium Backend version

3.3.4

### Selenium version

4.9.0

### Logs appeared during using Healenium

```shell
NA
```

### Additional context

this is my screenshot of docker.

![Screenshot (202)](https://github.com/healenium/healenium-example-maven/assets/141708930/531c42b4-d228-430e-9521-8e4dfc9aef41)
![Screenshot (203)](https://github.com/healenium/healenium-example-maven/assets/141708930/f63406a5-f8ab-4a0c-9d34-8578b9db48fc)

if you want to contact me for the help you can directly ping me on my mail :- aaddaarrsshh97@gmail.com
please healp

**Comment by adarsh12308** [comment]
Anyone please help because it's urgent

**Comment by Alex-Reif** [comment]
Hello @adarsh12308 , First off thanks for project and logs.
As I can see by logs:
2023-09-11 01:03:24.906  INFO 1 - [7878-exec-3] healenium                        : [Save Elements] Request: By.cssSelector([name='Email']) 
2023-09-11 01:09:29.531  INFO 1 - [7878-exec-7] healenium                        : [Get Reference] Request: RequestDto(locator=[name='Email'], className=demoHealenium.HealeniumDemoWithDocker, methodName=healeniumDemoWithDocker, command=findElement, url=http://6596641.tilda.ws/)) 
2023-09-11 01:11:26.603  INFO 1 - [7878-exec-1] healenium                        : [Save Elements] Request: By.cssSelector([name='Email']) 
2023-09-11 01:11:27.983  INFO 1 - [7878-exec-3] healenium                        : [Get Reference] Request: RequestDto(locator=[name='Name'], className=demoHealenium.HealeniumDemoWithDocker, methodName=healeniumDemoWithDocker, command=findElement, url=http://6596641.tilda.ws/)) 

Your locator was changed on the page and not in code. You didn't find element (name='Name') before that to store in the database as reference. Kindly run test suits successful to store all locators participated in the tests. And After that you can change locator on the page and Healenium will try to heal one.

**Comment by adarsh12308** [comment]
Can we catch the healed locators from docker to show in my extent report if yes then how

**Comment by AdarshSingh003** [comment]
Hello Healenium/Healenium-Example-Maven,

I am not able to get the report on local host 7878 port on same project can
you tell me please it's very urgent please

Thanks & Regards
Adarsh Singh

**Comment by nikpl8527** [comment]
Facing the same issue
